apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo-server
  name: echo-server-svc
spec:
  ports:
    - name: "echo-server"
      port: 8080
      protocol: TCP
      targetPort: 5678
  selector:
    app: echo-server
