apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test
spec:
  containers:
    - name: test
      image: hashicorp/http-echo:0.2.3
      args:
        - "-text=this is test"
  restartPolicy: Never
status: {}